#! /bin/sh

#qemu-system-x86_64 -L . -m 64 -fda /home/estai/workspace/EST64OS/Disk.img -localtime -M pc

qemu-system-x86_64 -L . -m 64 -drive file=/home/estai/workspace/EST64OS/Disk.img,index=0,if=floppy,format=raw -localtime -M pc
